### YamlMime:ModuleUnit
uid: learn.principles-cloud-computing.4-cloud-deployment-models
title: <span data-ttu-id="5efca-101">Distributionsmodeller för molnet</span><span class="sxs-lookup"><span data-stu-id="5efca-101">Cloud deployment models</span></span>
metadata:
  title: <span data-ttu-id="5efca-102">Distributionsmodeller för molnet</span><span class="sxs-lookup"><span data-stu-id="5efca-102">Cloud deployment models</span></span>
  description: <span data-ttu-id="5efca-103">Distributionsmodeller för molnet</span><span class="sxs-lookup"><span data-stu-id="5efca-103">Cloud deployment models</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 80c9a95833f8fb5be1e0e89b4729b0c5de07a7d2
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47150220"
durationInMinutes: 10
content: '[!include[](includes/4-cloud-deployment-models.md)]'
