### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: Aktivera och konfigurera diskcache för virtuella Azure-datorer med Azure Portal
metadata:
  title: Aktivera och konfigurera diskcache för virtuella Azure-datorer med Azure Portal
  description: Aktivera och konfigurera diskcache för virtuella Azure-datorer med Azure Portal
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 20238bbb5638ea2e5985a7a51e5885700f64099b
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47149176"
durationInMinutes: 5
content: '[!include[](includes/3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)'
