### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: Identifiera flaskhalsar i appars prestanda
metadata:
  title: Identifiera flaskhalsar i appars prestanda
  description: I den här utbildningsenheten går vi igenom hur du kan identifiera flaskhalsar i appars prestanda
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: c7d8f1f8564a139f58fb17efc300af92e96cf906
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47150601"
durationInMinutes: 9
content: >
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: Testa dina kunskaper
  questions:
  - content: Vilket av följande alternativ beskriver bäst Application Insights?
    choices:
    - content: En enda vy för alla dina övervakningsbehov i Azure
      isCorrect: false
      incorrectExplanation: Även om Application Insights kan ge mängder av information om ditt programprestanda så är det inte en heltäckande Azure-övervakningslösning.
    - content: En implementering av övervakningsmönstret för slutpunktens tillstånd
      isCorrect: false
      incorrectExplanation: Övervakningsmönstret för slutpunktens tillstånd fokuserar på att övervaka den övergripande hälsan för slutpunkter som exponeras av ditt program.
    - content: En arbetsyta där du kan samla loggar från olika appar och delar av infrastrukturen
      isCorrect: false
      incorrectExplanation: Log Analytics är en arbetsyta där du kan samla loggar från olika appar och delar av infrastrukturen.
    - content: En tjänst som övervakar webbprogrammens tillgänglighet, prestanda och användning
      isCorrect: true
      correctExplanation: Application Insights är en tjänst som övervakar webbprogrammens tillgänglighet, prestanda och användning.
  - content: 'Sant eller falskt: Log Analytics spårar anpassade loggar och mått.'
    choices:
    - content: Sant
      isCorrect: true
      correctExplanation: När det gäller anpassade loggar och mått kan du använda HTTP-datainsamlarens API till att skriva data till Log Analytics från valfri REST API-klient, eller en Azure Logic App till att skriva data från ett anpassat arbetsflöde.
    - content: Falskt
      isCorrect: false
      incorrectExplanation: När det gäller anpassade loggar och mått kan du använda HTTP-datainsamlarens API till att skriva data till Log Analytics från valfri REST API-klient, eller en Azure Logic App till att skriva data från ett anpassat arbetsflöde.
