### YamlMime:ModuleUnit
uid: learn.secure-your-azure-virtual-machine-disks.6-exercise-automate-secure-vm-deployments-using-arm-templates
title: <span data-ttu-id="3bbb5-101">Övning – automatisera säkra distributioner av virtuella datorer genom att lägga till kryptering i Azure Resource Manager-mallar</span><span class="sxs-lookup"><span data-stu-id="3bbb5-101">Exercise - Automate secure VM deployments by adding encryption to Azure Resource Manager templates</span></span>
metadata:
  title: <span data-ttu-id="3bbb5-102">Övning – automatisera säkra distributioner av virtuella datorer genom att lägga till kryptering i Azure Resource Manager-mallar</span><span class="sxs-lookup"><span data-stu-id="3bbb5-102">Exercise - Automate secure VM deployments by adding encryption to Azure Resource Manager templates</span></span>
  description: <span data-ttu-id="3bbb5-103">Övning – automatisera säkra distributioner av virtuella datorer genom att lägga till kryptering i Azure Resource Manager-mallar</span><span class="sxs-lookup"><span data-stu-id="3bbb5-103">Exercise - Automate secure VM deployments by adding encryption to Azure Resource Manager templates</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 1f3bd0f030eaa532d3a9515bd9634404d13b4d10
  ms.sourcegitcommit: 58e9d7fbb111af9b27ed819e4b79ba4a4e6e8a9c
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/21/2018
  ms.locfileid: "46514567"
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/6-exercise-automate-secure-vm-deployments-using-arm-templates.md)]'
