### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: Nätverkssäkerhet
metadata:
  title: Nätverkssäkerhet
  description: I den här kursdelen ska vi titta närmare på hur du skyddar din nätverksinfrastruktur
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: cc35a096e064136f7d56fc05c4ce856fd1918641
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47150049"
durationInMinutes: 10
content: >
  [!include[](includes/6-network-security.md)]
quiz:
  title: Testa dina kunskaper
  questions:
  - content: Azure nätverkssäkerhetsgruppen kan användas för att skydda kommunikationen mellan vilka av följande?
    choices:
    - content: Virtuella datorer och Internet
      isCorrect: false
      incorrectExplanation: Nätverkssäkerhetsgrupper är helt anpassningsbara och ger dig möjlighet att fullständigt låsa nätverkskommunikation till och från virtuella datorer.
    - content: Virtuella datorer inom ett virtuellt nätverk
      isCorrect: false
      incorrectExplanation: Nätverkssäkerhetsgrupper är helt anpassningsbara och ger dig möjlighet att fullständigt låsa nätverkskommunikation till och från virtuella datorer.
    - content: System i ett lokalt nätverk
      isCorrect: false
      incorrectExplanation: Nätverkssäkerhetsgrupper är helt anpassningsbara och ger dig möjlighet att fullständigt låsa nätverkskommunikation till och från virtuella datorer.
    - content: Alla alternativ ovan
      isCorrect: true
      correctExplanation: Nätverkssäkerhetsgrupper är helt anpassningsbara och ger dig möjlighet att fullständigt låsa nätverkskommunikation till och från virtuella datorer.
  - content: Vilket av följande är inte en metod för att skydda Internetriktade tjänster mot nätverksangrepp?
    choices:
    - content: Azure DDoS
      isCorrect: false
      incorrectExplanation: Azure Disk Encryption skyddar din virtuella dators virtuella hårddiskar från exponering, men ger inget skydd mot nätverksbaserade angrepp.
    - content: Azure Application Gateway WAF
      isCorrect: false
      incorrectExplanation: Azure Disk Encryption skyddar din virtuella dators virtuella hårddiskar från exponering, men ger inget skydd mot nätverksbaserade angrepp.
    - content: Azure Disk Encryption
      isCorrect: true
      correctExplanation: Azure Disk Encryption skyddar din virtuella dators virtuella hårddiskar från exponering, men ger inget skydd mot nätverksbaserade angrepp.
    - content: En virtuell nätverksinstallation
      isCorrect: false
      incorrectExplanation: Azure Disk Encryption skyddar din virtuella dators virtuella hårddiskar från exponering, men ger inget skydd mot nätverksbaserade angrepp.
