### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.5-configure-rules-and-actions
title: <span data-ttu-id="7b1e7-101">Konfigurera regler och åtgärder för att övervaka din kaffebryggare</span><span class="sxs-lookup"><span data-stu-id="7b1e7-101">Configure rules and actions to monitor your coffee machine</span></span>
metadata:
  title: <span data-ttu-id="7b1e7-102">Konfigurera regler och åtgärder för att övervaka din kaffebryggare</span><span class="sxs-lookup"><span data-stu-id="7b1e7-102">Configure rules and actions to monitor your coffee machine</span></span>
  description: <span data-ttu-id="7b1e7-103">Konfigurera regler och åtgärder för att övervaka din kaffebryggare</span><span class="sxs-lookup"><span data-stu-id="7b1e7-103">Configure rules and actions to monitor your coffee machine</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 5a6343fe6bbbe47ec15d343ce3e448315a27f606
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: sv-SE
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47154546"
durationInMinutes: 12
content: '[!include[](includes/5-configure-rules-and-actions.md)]'
